name: Docker Image CI

on:
  schedule:
    - cron: 0 18 * * *  # Runs the job every hour at the 0th minute
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ngangastanley/cypress_test1:latest
